package cz.cvut.fel.x33eja.chalupa.eshop.model;

// Generated Jan 17, 2011 2:57:03 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.jboss.seam.annotations.security.management.UserRoles;

/**
 * Administrators generated by hbm2java
 */
@Entity
@Table(name = "administrators")
public class Administrator extends User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -165835638638417769L;
	private boolean archived;
	private Set<Product> products = new HashSet<Product>(0);
	private Set<Photo> photos = new HashSet<Photo>(0);
	private Set<Role> roles = new HashSet<Role>(0);

	public Administrator() {
	}

	public Administrator(boolean archived) {
		this.archived = archived;
	}

	public Administrator(boolean archived, Set<Product> products,
			Set<Photo> photos) {
		this.archived = archived;
		this.products = products;
		this.photos = photos;
	}

	@Column(name = "archived", nullable = false)
	public boolean isArchived() {
		return this.archived;
	}

	public void setArchived(boolean archived) {
		this.archived = archived;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "administrators")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "administrator")
	public Set<Photo> getPhotos() {
		return this.photos;
	}

	public void setPhotos(Set<Photo> photos) {
		this.photos = photos;
	}

	@UserRoles
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "administrator_role", joinColumns = { @JoinColumn(name = "administrator") }, inverseJoinColumns = { @JoinColumn(name = "role") })
	public Set<Role> getRoles() {
		return roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

}
