package cz.cvut.fel.x33eja.chalupa.eshop.model;

// Generated Jan 17, 2011 2:57:03 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * OrderLineItem generated by hbm2java
 */
@Entity
@Table(name = "order_line_items")
public class OrderLineItem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6239951164100296232L;
	private Long id;
	private Product product;
	private Order orders;
	private int count;

	public OrderLineItem() {
	}

	public OrderLineItem(Long id, Product product, Order orders, int count) {
		this.id = id;
		this.product = product;
		this.orders = orders;
		this.count = count;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product", nullable = false)
	@NotNull
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "purchase_order", nullable = false)
	@NotNull
	public Order getOrders() {
		return this.orders;
	}

	public void setOrders(Order orders) {
		this.orders = orders;
	}

	@Column(name = "count", nullable = false)
	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

}
